FROM openjdk:8
ADD ./tar/zscmp-vm.jar app.jar

# 修改容器内的时区
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

# 各个参数按情况可自行修改
ENTRYPOINT ["java","-Xms128m", "-Xmx1g","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5010","/app.jar","--db.url=jdbc:mariadb://localhost:3306/zscmp_vm?useUnicode=true&characterEncoding=utf8&useMysqlMetadata=true","--db.password=password"]