FROM openjdk:17.0.1
ADD ./tar/zscmp-connector.jar app.jar

# 修改容器内的时区
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

# 各个参数按情况可自行修改
ENTRYPOINT ["java","--add-opens=java.base/java.lang=ALL-UNNAMED","-Xms128m", "-Xmx512m","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5013","/app.jar","--db.password=password"]