# cmp用docker部署的配置
version: "3.9"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile-base
    network_mode: "host"
    volumes:
      - /usr/local/zstack-cmp:/usr/local/zstack-cmp
      - /root/cmp:/usr/local/zstack-cmp/upload/sourceCode
      - /sbin/dmidecode:/sbin/dmidecode
      - /dev/mem:/dev/me
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8101/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 12
    depends_on:
      - mariadb
      - rabbitmq
      - redis
      - nacos


  mariadb:
    image: mariadb:10.8.2
    volumes:
      - ./config/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./config/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: password
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:management-alpine
    network_mode: "host"
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "host"
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf

  nacos:
    image: nacos/nacos-server:v2.2.3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8848/nacos/v1/console/health/readiness"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 3
    network_mode: "host"
    environment:
      - MODE=standalone