FROM openjdk:8
ADD ./tar/zscmp-base.jar app.jar

# 修改容器内的时区
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

# 各个参数按情况可自行修改
ENTRYPOINT ["java","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005","/app.jar","--db.password=password", "--firstLaunchInit.locale=zh_CN"]